/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { Donation } from "./Donation";
import { DonationCountArgs } from "./DonationCountArgs";
import { DonationFindManyArgs } from "./DonationFindManyArgs";
import { DonationFindUniqueArgs } from "./DonationFindUniqueArgs";
import { CreateDonationArgs } from "./CreateDonationArgs";
import { UpdateDonationArgs } from "./UpdateDonationArgs";
import { DeleteDonationArgs } from "./DeleteDonationArgs";
import { DonationService } from "../donation.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => Donation)
export class DonationResolverBase {
  constructor(
    protected readonly service: DonationService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "Donation",
    action: "read",
    possession: "any",
  })
  async _donationsMeta(
    @graphql.Args() args: DonationCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [Donation])
  @nestAccessControl.UseRoles({
    resource: "Donation",
    action: "read",
    possession: "any",
  })
  async donations(
    @graphql.Args() args: DonationFindManyArgs
  ): Promise<Donation[]> {
    return this.service.donations(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => Donation, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "Donation",
    action: "read",
    possession: "own",
  })
  async donation(
    @graphql.Args() args: DonationFindUniqueArgs
  ): Promise<Donation | null> {
    const result = await this.service.donation(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Donation)
  @nestAccessControl.UseRoles({
    resource: "Donation",
    action: "create",
    possession: "any",
  })
  async createDonation(
    @graphql.Args() args: CreateDonationArgs
  ): Promise<Donation> {
    return await this.service.createDonation({
      ...args,
      data: args.data,
    });
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Donation)
  @nestAccessControl.UseRoles({
    resource: "Donation",
    action: "update",
    possession: "any",
  })
  async updateDonation(
    @graphql.Args() args: UpdateDonationArgs
  ): Promise<Donation | null> {
    try {
      return await this.service.updateDonation({
        ...args,
        data: args.data,
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Donation)
  @nestAccessControl.UseRoles({
    resource: "Donation",
    action: "delete",
    possession: "any",
  })
  async deleteDonation(
    @graphql.Args() args: DeleteDonationArgs
  ): Promise<Donation | null> {
    try {
      return await this.service.deleteDonation(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
