/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { News } from "./News";
import { NewsCountArgs } from "./NewsCountArgs";
import { NewsFindManyArgs } from "./NewsFindManyArgs";
import { NewsFindUniqueArgs } from "./NewsFindUniqueArgs";
import { CreateNewsArgs } from "./CreateNewsArgs";
import { UpdateNewsArgs } from "./UpdateNewsArgs";
import { DeleteNewsArgs } from "./DeleteNewsArgs";
import { NewsService } from "../news.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => News)
export class NewsResolverBase {
  constructor(
    protected readonly service: NewsService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "News",
    action: "read",
    possession: "any",
  })
  async _newsItemsMeta(
    @graphql.Args() args: NewsCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [News])
  @nestAccessControl.UseRoles({
    resource: "News",
    action: "read",
    possession: "any",
  })
  async newsItems(@graphql.Args() args: NewsFindManyArgs): Promise<News[]> {
    return this.service.newsItems(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => News, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "News",
    action: "read",
    possession: "own",
  })
  async news(@graphql.Args() args: NewsFindUniqueArgs): Promise<News | null> {
    const result = await this.service.news(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => News)
  @nestAccessControl.UseRoles({
    resource: "News",
    action: "create",
    possession: "any",
  })
  async createNews(@graphql.Args() args: CreateNewsArgs): Promise<News> {
    return await this.service.createNews({
      ...args,
      data: args.data,
    });
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => News)
  @nestAccessControl.UseRoles({
    resource: "News",
    action: "update",
    possession: "any",
  })
  async updateNews(@graphql.Args() args: UpdateNewsArgs): Promise<News | null> {
    try {
      return await this.service.updateNews({
        ...args,
        data: args.data,
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => News)
  @nestAccessControl.UseRoles({
    resource: "News",
    action: "delete",
    possession: "any",
  })
  async deleteNews(@graphql.Args() args: DeleteNewsArgs): Promise<News | null> {
    try {
      return await this.service.deleteNews(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
